service: email-api

provider:
  name: aws
  runtime: nodejs18.x

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - http:
          path: send-email
          method: post
          cors: true

plugins:
  - serverless-offline
